apiVersion: v1	
kind: PersistentVolume	
metadata:	
  name: "efs-pv"	
spec:	
  capacity:	
    storage: 30Gi	
  accessModes:	
  - ReadWriteMany	
  persistentVolumeReclaimPolicy: Retain	
  volumeMode: Filesystem	
  storageClassName: standard-rwo	
  nfs:	
    path: {{ .Values.volume.path }}	
    server: {{ .Values.volume.server }} 