apiVersion: v1
kind: PersistentVolume
metadata:
  name: "gke-pv"
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
  labels:
    name: "gke-pv"
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: nfs-client
  nfs:
    path: {{ .Values.volume.path }}
    server: {{ .Values.volume.server }}
