apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-filestore
provisioner: filestore.csi.storage.gke.io
parameters:
  # "CIDR range to allocate Filestore IP Ranges from"
  reserved-ipv4-cidr: {{ .Values.storage.reservedIpRange }}
  # # standard (default) or premier
  tier: default
  # # Name of the VPC. Note that non-default VPCs require special firewall rules to be setup: TODO
  network: {{ .Values.storage.network }}
allowVolumeExpansion: true
reclaimPolicy: Retain