apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gke-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  selector:
    matchLabels:
      name: "gke-pv"
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 50Gi
