apiVersion: v1
kind: PersistentVolume
metadata:
  name: "efs-pv"
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs"
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: gke-csi-filestore
  nfs:
    path: {{ .Values.volume.path }}
    server: {{ .Values.volume.server }}
