imports:
- path: boomi-network.jinja

resources:
- name: boomi-network
  type: boomi-network.jinja
  properties:
    region: us-central1
    publicSubnetCIDR: 101.0.0.0/20
    privateSubnetCIDR: 101.0.16.0/20