imports:
- path: ../boomi_molecule.jinja

resources:
- name: boomi-gke-quickstart
  type: boomi_molecule.jinja
  properties:
    zone: us-central1-a
    boomiUserEmailID: vilvamani007@gmail.com
    boomiPassword: google#2020
    boomiAccountID: google-microsoft
