apiVersion: v1
kind: PersistentVolume
metadata:
  name: "efs-pv"
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /boomifileshare
    server: ip-address